lib/transaction.py
decode_claim_script function should accept Op code 0 (OP_0) to push data as is allowed in Core ( see https://github.com/lbryio/lbrycrd/blob/master/src/nameclaim.cpp#L58 ) 
This fixes a bug where getvalueforname('') will raise an exception.
=> fixing decode_claim_script to accept OP_0

lib/commands.py
Function decode_claim_script returns False if it failed to decode a claim script, account for this case.
=> Account for case where decode_claim_script could return False

lib/commands.py, lib/lbrycrd.py
Requesting value of a name at current height is not secure, as someone can create a single block with whatever claimtrie they wanted.  This is the equivalent of waiting for six confirms for a cryptocurrency transaction.
=> Command getvalueforname should look back six confirms for security

lib/commands.py, lib/wallet.py
For https://github.com/lbryio/lbryum/issues/29
This adds an option exclude_claimtrietx to getbalance command. If set to True, the balance will exclude any lbry credits used for claimtrie transactions. It is set to False by default.
=> adding option in getbalance command to exclude claimtrie transactions

lib/commands.py
add_transaction should not be used here, 
as lbryum will broadcast this first, get the transaction back, and than it will call receive_tx_callback which will call add_transaction, save_transaction, and add_unverified_tx
Calling add_transaction prematurely here will screw things up.
=> add_transaction should not be used here

lib/lbrycrd.py, lib/tests/test_lbry.py, lib/wallet.py
This adds a claim id hash function, necessary for obtaining the claim id from the txid and nout.  
Add the calculated claim id to getnameclaims for claims. 
Minor fix to add a missed assert in the unit test for verify_proof function.
=> adding claim id hash function, adds claim_id in getnameclaims

lib/commands.py, lib/transaction.py
Ordering of claim_id and claim_val was mixed up in wallet.py,transaction.py, and commands.py for update claim outputs. wallet.py used ordering of (claim_name,claim_id,claim_val) while the rest used (claim_name,claim_val,claim_id)
I chose to use the ordering of (claim_name,claim_id,claim_val) since that is the actual order in which they appear in an update transaction.
=> fixing order of claim_id and claim_val for updates

lib/blockchain.py, lib/network.py
lbryum bootstraps fine when the chain is long enough that it switches
over to requesting the headers in chunks.
But for a short chain, it fails due to a few reasons.  This commit
fixes those.
=> Allow lbryum to download and save the genesis block

lib/__init__.py, lib/network.py, lib/simple_config.py, lib/tests/test_simple_config.py
Even worse, the ONLINE_SERVERS variable was calculated at import time
making it very difficult to change by a caller.  I got rid of that
too.
Instead, it has been replaced by adding a default_config item to the
simple_config, which should allow callers more control.
=> Eliminate the DEFAULT_SERVERS constant.

lib/lbrycrd.py, lib/wallet.py
Add a function to encode claim id bytes into hex string, and decode hex strings into claim id bytes. 
Change getnameclaims() command to return the claim id's in hex string and return "update","support","claim" for "category"
=> adding claim id decode/encode functions, fixing get_name_claim function

lib/util.py
the logger already has the option to add in a timestamp, removing the redundant manual one.
=> remove redundant timestamp from log

lib/commands.py
For getvalueforname, instead of returning an ambiguous dictionary " {'value':{}} ", return an error in case name has no claims attached to it.
=> return error in case name is not claimed for getvalueforname

lib/network.py
Currently, Auto connect does not immediately connect to a functioning server on startup, if the default server is not reachable / disconnected. 
This fixes the auto connect function, based on 
https://github.com/spesmilo/electrum/commit/6f72fa4e94434950d56a556d7c30b3ac855631ca
https://github.com/spesmilo/electrum/commit/4dd479cf59a82066faedd8c0f0f816419ab31746
It also removes unused function new_blockchain_height
=> Fixing autoconnect fuction in network

lib/commands.py, lib/lbrycrd.py, lib/wallet.py
New abandon command with several new features:
This utilizes both txid and nOut to pickout the proper claimtrie tx to abandon (just txid is not sufficient)
It does not take amount as input, as the amount to abandon should be calculated automatically, and it does not make sense to abandon less or more than what is being used for the claim.  
It adds the transaction to the wallet, and broadcasts it over the network, so callers of this function (specifically lbrynet) do not need to mess with that. 
It does not use mktx or get_spendable_coins , instead it uses a new wallet function get_spendable_claimtrietx_coin to get the correct unspent, and will only use that unspent which will than be emptied into a new return address if the return address was not specified. 
Further work needed:
Fix …
=> new abandon command with txid and nOut

lib/claims.py
This was an abuse of assertions. In theory, assertions could be removed
from code and it would function exactly the same. Also, when the
assertion fails, an AssertionError is raised, not the desired
InvalidProofError.
=> raise InvalidProofError

lib/commands.py, lib/tests/test_lbry.py
Lbryum is not designed to be thread safe. We need to have lbrynet use lbryum in a single threaded manner, except in the case of when lbryum makes a network call to lbryum-server, which can be called on a separate thread asynchronously. 
https://github.com/lbryio/lbryum/commit/ad0662e6b858c48f4c6a180d94d2399347bcc880
This commit adds a broadcast option to the claim command, separating the act of making a transaction, and broadcasting a transaction (  broadcasting a transaction is just a send to lbyum server ). 
https://github.com/lbryio/lbryum/commit/e5fd46e7aa41003248fb77fc9f277c0d0205a432
This commit reorganizes getvalueforname command into multiple functions. getvaluforname command makes a lbryum server call and also accesses internal state.  Thus lbrynet needs to be able to do these …
=> Fix lbrynet concurrency issues

lib/commands.py, lib/tests/test_commands.py
This catches NotEnoughFunds (happens when there is not enough available credits to make a claim) exception when making claim transactions so they can be return instead in the Json output. 
In Lbrynet when making a claim , this code here will now catch the case when there is not enough funds https://github.com/lbryio/lbry/blob/master/lbrynet/core/Wallet.py#L481
=> catch NotEnoughFunds exception when making claim transactions

lib/commands.py
getvalueforname was looking back six blocks from the tip, but only needs to look back five, because the current tip counts as a confirm (i.e, if we are on block 50 , the claims on block 50 has 1 confirm, the claims on block 49 has 2 confirms, etc..)
=> Fixing bug in getvalueforname

lib/__init__.py
Libraries don't get to configure their own logging. The caller
configures logging.
=> Remove logging configuration

lib/network.py
I have ~850 addresses in my wallet and sending subscriptions for each
one takes more than 10 seconds. There is probably a better solution...
=> Increase timeout

lib/lbrycrd.py
Change recommended confirms for claimtrie commands to be 1, instead of 6. 
Used when calling getvalueforname command to lbryum server. 
Trade off for more responsiveness, over security.
=> Change recommended confirms for claimtrie commands

lib/network.py
This prevents a non-responsive lbryum request from blocking lbrynet-daemon or the app from shutting down
=> set default timeout to 30s for lbryum requests

lib/commands.py
The claim command returns the claim ID in a dictionary with the key "claimid". Other claimtrie command uses the key "claim_id" to refer to the claim ID so make it consistent and use "claim_id".
=> Fix claimid return as claim_id for consistency

CHANGELOG.md, lib/wallet.py
wallet.get_spendable_coins() could return coins that were being used either as a support or an update (although it was properly filtering claims), thus wallet could end up abandoning a support or an update when making a new transaction (either a regular send, or a claimtrie transaction)
You can test this easily through lbryum console by typing wallet.get_spendable_coins() , before this pull request, you could clearly see supports and updates being returned as spendable.
=> Make supports and updates not spendable

CHANGELOG.md, lib/network.py
This fixes the way lbryum requests chunks .
Lbryum will automatically start requesting chunks if it needed more blocks than was in a chunk. However after finishing requesting chunks, it also needed to download the left over headers that did not fit into a chunk ( say  lbryum needs to download 25 blocks and each chunk contained 10 blocks. It would download the first 2 chunks and 20 blocks, but the other 5 would not be downloaded). The leftover blocks would not be downloaded until the lbryum server announced a new height, which happens when a block is mined and that can take two mintues on average. This would make startup time take much longer than usual.
This patch starts requesting individual headers immediately after requesting chunks. It will fix lbry-in-a-oox integration testing which …
=> Request individual headers when finished requesting chunks

lib/network.py
Catch Queue.Empty exception when queue.get() operation times out in synchronous_get() and throw an exception that is more informative.
=> catch Queue.Empty in synchronous_get

CHANGELOG.md, lib/commands.py, lib/daemon.py, lib/plugins.py, setup.py
It is necessary to launch lbryum as a seperate process from lbrynet, instead of using it as a library. This is the required prep work needed in lbryum. 
commands.py adds functions that are currently defined in lbrynet.core.Wallets, since lbrynet will need to perform all interactions with lbryum through JSON RPC functions defined in commands.py
daemon.py now loads the wallet upon initialization.  
Have setup.py install lbryum as a script. 
Fixed bug in plugins.py which prevented running lbryum as an installed script.
=> Prep work to seperate lbryum process

CHANGELOG.md, lib/commands.py
Claim id's should be decoded , updates don't work without this change.
=> Fix bug in update

CHANGELOG.md, lib/commands.py, lib/tests/test_commands.py, lib/wallet.py
getcertificateclaims() command needs list of claims with excluded supports. 
updateclaimsignature() command needs list of claims with excluded supports
claim() commands needs list of claims with excluded supports
Added include_supports argument to Wallet.get_name_claims(). Also added include_abandoned argument to Wallet.get_name_claims() since that was a common argument that other commands required. 
getnameclaims() command has include_supports argument.
=> Fix bugs related to get_name_claims() returning supports

lbryum, lib/commands.py, lib/daemon.py
These changes allow lbryum to run in daemon mode, specifically for use in lbry in a box integration testing. 
Will not affect functionality in lbrynet.
Change in file lbryum allow us to decode all output from daemon as json. 
Change in file lib/commands.py allow us to specify lbryum data path from the command line, for example by calling ./lbryum daemon start -D /pathto/data
Change in lib/daemon.py allow us to create a wallet upon startup of the daemon
=> Changes for running lbryum in daemon mode

CHANGELOG.md, lib/commands.py
claim_id variable in update command is already a hex encoded string
=> fix claim_id output in update command

lib/commands.py
claimcertificate calls claim, which could return without 'claim_id' field if claim failed and 'success' is false
If claim fails, just return the result from claim without calling wallet.save_certificate or wallet.set_default_certificate
=> fix claimcertificate incase claim fails

CHANGELOG.md, lib/commands.py
This command will wait until the transaction with txid appears in wallet. 
Needed for testing, but could also be used to avoid double spends when sequentially making transactions.
=> add waitfortxinwallet command

CHANGELOG.md, lib/commands.py
abandon command needs to also take txid/nout as input argument if you want to abandon supports. 
Also, instead of using getclaimbyid(), which is a lbryum server call, it should use getnameclaims() which is a wallet call (faster, safer, and don't need to wait for a confirm before abandoning something) 
Added arguments claim_id, txid, and nout to getnameclaims() function that allow you to filter the claims. Also use this new feature when calling getnameclaims() from sendclaimtoaddress to filter by claim_id.
=> Fix abandon

CHANGELOG.md, lib/commands.py
Change error 'nothing to resolve' in getvalueforuri() to 'claim not found' used in other places. 
This applies to when searching for a claim sequence that does not exist (i.e. sometnameclaim:100 )
=> change 'nothing to resolve' error to 'claim not found' 

CHANGELOG.md, lbryum/commands.py
getclaimbyoutpoint will throw an exception if there is no claim attached to txid (claims becomes None and None is not iterable). 
Return None if no claim exists at txid
=> Fix getclaimbyoutpoint if no claim exists at outpoint

lbryum/commands.py
Supports and amounts were not being properly formatted when calling getvalueforuris in certain situations. 
Makes sure that format_amount_value is called on every response.
This should fix https://github.com/lbryio/lbry/issues/713 and partially fix https://github.com/lbryio/lbry/issues/750
=> Format response in getvalueforuris

CHANGELOG.md, lbryum/commands.py
Now, while resolving channel names, no of claims are returned, not no of pages.
Fixes lbryio/lbry#691
=> Resolving a channel returns 'channel_claim_count'

CHANGELOG.md, lbryum/wallet.py
While testing lbry-in-a-box, I discovered that a race condition could cause you to create the same address in your wallet twice. 
This is because the synchronizer, which runs on a seperate thread, will attempt to create a new address if more is needed. : https://github.com/lbryio/lbryum/blob/83e1d5ce1746397b41c66a5500322641f95bf7fd/lbryum/account.py#L67
If you call Wallet.create_new_address() while the synchrhonizer is creating a new address, than you could end up creating two keys from the same n, since n is dependent on how many addresses you have already created.  https://github.com/lbryio/lbryum/blob/83e1d5ce1746397b41c66a5500322641f95bf7fd/lbryum/account.py#L44
Put a lock on Wallet.create_new_address() , since we already have a lock on Wallet.synchronize() , this should be sufficient …
=> Fix create new address race

CHANGELOG.md, lbryum/account.py, lbryum/wallet.py, tests/test_account.py
Duplicate addresses in the wallet could be created due to a race condition (https://github.com/lbryio/lbryum/pull/147). Also implied is that the duplicate address causes a missing address since BIP32 generates keys sequentially in deterministic manner. This is because when creating a new address, the BIP32 account will check how many addresses it already has to determine what sequence number the new address should use:
https://github.com/lbryio/lbryum/blob/7be85f4b12d9fe353b7e262db6e69ed1eb80760c/lbryum/account.py#L49
This PR detects if there are problems in the wallet due to this, and corrects it when Wallet is initializing. Detection is fast (look for duplicate keys and also check if pubkey[-1] is equal to derive_pubkey( sequence_number=len(pubkey)-1 ) but correction can take a minute …
=> Correct duplicate addresses in wallet

CHANGELOG.md, lbryum/commands.py
This changes the `getnameclaims` command to not use the inefficient (and soon deprecated) `parse_and_validate_claim_result` function when formatting claim infos. It also adds a parameter to `getnameclaims` to disable signature validation, which slows down `claim`, `update`, `abandon`, and `claimcertificate` significantly - and is not necessary since `getnameclaims` is only being used to prevent making duplicate claims or to find a particular claim in those functions. 
By default `getnameclaims` validates claim signatures, using the more efficient `getclaimsbyids` command to retrieve any certificates not in the wallet (previously all certificates were requested even if they were in the wallet). In the claim related commands where signature validation isn't needed, it is skipped.
Using a …
=> Fast getnameclaims, speed up commands used to issue claims

CHANGELOG.md, lbryum/commands.py, lbryum/wallet.py, tests/test_commands.py
* Improved speed of `getunusedaddress`
* Moved storage.write call in `getunusedaddress` to `Deterministic_Wallet`
* By default use the least used change address rather than generating new ones for claims
* Added `getleastusedchangeaddress` command
=> Address improvements

CHANGELOG.md, lbryum/commands.py, lbryum/wallet.py, tests/test_commands.py
This adds a general get_least_used_address function to the wallet, and a `getleastusedaddress` command.
Additionally, when getting a least used address, only those with a history count less than 100 will be considered - this is to lower the memory requirement for indexing the utxos by addresses
=> add getleastusedaddress, better address usage

CHANGELOG.md, lbryum/wallet.py
This fixes issue: https://github.com/lbryio/lbryum/issues/182
The reason why this was happening was because WalletStorage.write() is called by the network loop, which is on separate thread then the daemon (which handles commands)  and it does not acquire a lock when doing so. If you called WalletStorage.write() on the daemon thread, you ran into a race condition when WalletStorage.write() was also being called on the network loop simultaneously.
In the channel claim command, it saves the wallet immediately after creating the certificate which happened to coincide on a semi frequent basis to when the wallet would get saved by the network loop after receiving the transaction from servers.
Use WalletStorage.lock when doing WalletStroage.write() , you can see that this is done on the latest …
=> Fix wallet storage write

CHANGELOG.md, lbryum/commands.py
Fixes https://github.com/lbryio/lbryum/issues/194
paytoandsend, paytomanyandsend has been removed in favor of using the broadcast argument in payto and paytomany to be consistent with other commands. 
wallet.send_tx() is used instead of self.network.synchronous_get(('blockchain.transaction.broadcast', [str(tx)])) to avoid race conditions.
The output has been cleaned up to return more useful information.
Docstring has been added.
=> Rework payto, paytoandsend, paytomany, paytomanyandsend 

CHANGELOG.md, lbryum/commands.py, lbryum/main.py
* Fixed main account not being created by `restore`
* Added `no_password` parameter to `restore` command
* Added `--chain` parameter to command line to specify `lbrycrd_regtest` or `lbrycrd_testnet` instead of default `lbrycrd_main`
=> Fix restore command
