lbryio/lbryum

lib/network.py, lib/version.py
include more lbryum-server hosts
=> merge development into master

lib/bitcoin.py, lib/blockchain.py
corresponding PoW hash for https://github.com/lbryio/lbrycrd/pull/3
=> use new pow hash algo

gui/qt/main_window.py
This is the way i get the gui running
Otherwise a lot of broken references to bitcoin
`dunno@debian:~/git/lbryum$ ./lbryum gui
Traceback (most recent call last):
File "./lbryum", line 339, in <module>
gui.main()
File "/home/dunno/git/lbryum/gui/qt/__init__.py", line 184, in main
self.config.get('url')):
File "/home/dunno/git/lbryum/gui/qt/__init__.py", line 159, in start_new_window
w = self.create_window_for_wallet(wallet)
File "/home/dunno/git/lbryum/gui/qt/__init__.py", line 138, in create_window_for_wallet
w = ElectrumWindow(self, wallet)
File "/home/dunno/git/lbryum/gui/qt/main_window.py", line 182, in __init__
self.load_wallet(wallet)
File "/home/dunno/git/lbryum/gui/qt/main_window.py", line 293, in load_wallet
self.update_console()
File …
=> Update bitcoin to lbrycrd

lib/blockchain.py, lib/network.py
fixes bug where lbryum client is already up to date when it starts
=> Fix catchup

lib/commands.py, lib/version.py
adds getclaimsforname and has the amount returned in getvalueforname include supports
=> getclaimsforname

lib/claims.py, lib/tests/test_account.py, lib/tests/test_bitcoin.py, lib/tests/test_lbry.py, lib/tests/test_mnemonic.py, lib/tests/test_transaction.py, lib/tests/test_util.py, lib/transaction.py, lib/wizard.py
pull request for https://github.com/lbryio/lbryum/issues/21
=> changing imports to import from file not lbryum

lib/tests/test_lbry.py
This adds a unit test for the verify_proof function.
=> Add unit test for verify_proof function

lib/wallet.py
this adds field nOut for entries in the getnameclaims command, 
Related issue: 
https://github.com/lbryio/lbry/issues/147
=> this adds field nOut for getnameclaims command

lib/wallet.py
Saving claimtrie tx so get_balance will not throw exceptions on unverified transactions.
To solve https://github.com/lbryio/lbryum/issues/40
=> saving claimtrie transactions

lib/blockchain.py
This changes the difficulty calculation when using regtest mode. 
Regtest mode can be activated by adding an entry in the JSON config file ~/.lbryum/config 
The key is "chain" and value should be set to "regtest" ( "chain":"regtest" ). If "chain" value does not exist, lbryum assumes to be in mainnet (testnet uses same difficulty targeting as mainnet)
This patch should fix the below error that occurs when using lbryum from a lbryum server that is using regtest: 
[Blockchain] verify_chunk failed bits mismatch: 520159231 vs 545259519 (hash: 6e3fcf1299d4ec5d79c3a4c91d624a4acf9e2e173d95a1a0504f677669687556)
=> Change the difficulty calculation for regtest

gui/qt/paytoedit.py
This pull request fixes lbryum's qt inteface for sending 
( fixes https://github.com/lbryio/lbryum/issues/35)
=> Fixing send from lbryum interface

lib/commands.py
Add command to perform resolution by claim id through the lbryum server, requires https://github.com/lbryio/lbryum-server/pull/11
=> Add resolution by claim id 

lib/blockchain.py, lib/network.py
Taken from https://github.com/lbryio/lbryum/pull/53 , 
I would like to write a unit test for get_target() function later. But for now this pull request isn't having any issues on mainnet or regtest.
=> Refactor Blockchain class for handling regtest and testnet

CHANGELOG.md, lib/commands.py, lib/tests/test_commands.py, lib/wallet.py
Work on top of https://github.com/lbryio/lbryum/pull/87
Include additional fix to encode claim value output from lbrycrd into hex.
=> Hex encode claim value 2

CHANGELOG.md, lib/commands.py, lib/interface.py, lib/network.py, lib/simple_config.py, lib/tests/test_commands.py, lib/wallet.py, setup.py, tox.ini
https://github.com/lbryio/lbryum-server/pull/15
https://github.com/lbryio/lbry/pull/593
=> Integrate lbryschema

CHANGELOG.md, lib/blockchain.py, lib/lbrycrd.py, lib/network.py, lib/networks.py, lib/simple_config.py
fixes address prefixes being non-configurable
=> select blockchain in config

CHANGELOG.md, lib/commands.py, lib/simple_config.py
Goes with https://github.com/lbryio/lbryum-server/pull/31
=> Batched uri resolution

CHANGELOG.md, lib/commands.py
Fix for https://github.com/lbryio/lbry/issues/702
=> Fix transaction show

CHANGELOG.md, lbryum/commands.py
Fix https://github.com/lbryio/lbryum/issues/129
=> fix version command

CHANGELOG.md, lbryum/daemon.py, lbryum/network.py
Fix https://github.com/lbryio/lbryum/issues/128
=> fix status command

CHANGELOG.md, lbryum/commands.py
Required for lbryio/lbry-app#479
=> Reverse pagination

CHANGELOG.md, lbryum/lbrycrd.py, tests/test_lbry.py
lbryum has the same address validation bug as lbryschema: https://github.com/lbryio/lbryschema/issues/17
=> Fix address validation

CHANGELOG.md, lbryum/commands.py, lbryum/constants.py
* Removed `include_tip_info` argument from `history`
* Changed tip history to batch the claim queries it makes to improve performance
* Changed `history` to work offline
* Renamed `get_transaction_fee` to `transactionfee`
* Added `claimhistory` command
* Added `tiphistory` command
* Added `getclaimsbyids` with better batching of requests
=> Better batching and fast tip history

CHANGELOG.md, lbryum/__init__.py, lbryum/coinchooser.py, lbryum/commands.py, lbryum/main.py, lbryum/transaction.py, lbryum/wallet.py
https://github.com/lbryio/lbryum/issues/168
=> fix KeyError in claimhistory for transferred claim

lbryum/commands.py
Fixes https://github.com/lbryio/lbryum/issues/171
=> Fix getnameclaims to return non lbryschema claims 

.gitignore, CHANGELOG.md, lbryum/commands.py, lbryum/daemon.py, lbryum/main.py, requirements.txt, setup.py
Goes with https://github.com/lbryio/lbry/pull/783
=> Wallet encryption

CHANGELOG.md, lbryum/commands.py
@jackrobison This is the PR, for the abandon details showing in the txn list.
=> Abandon related info displayed in txn history

CHANGELOG.md, lbryum/commands.py
=> Include permanent_url in claim results.

lbryum/constants.py
this change will speed up first startups by up to 100%
=> Update headers URL

CHANGELOG.md, lbryum/commands.py
fixes https://github.com/lbryio/lbryum/issues/193
=> fix error in getnameclaims when a claim has an abandoned channel

CHANGELOG.md, lbryum/commands.py
fixes https://github.com/lbryio/lbry/issues/1231
=> fix wallet not be written to immediately after importing a certificate
